openapi: 3.0.0
info:
  title: NeordinaryU API
  version: 1.0.0
  description: NeordinaryU 백엔드 API 문서
paths:
  /:
    get:
      summary: Hello World
      responses:
        '200':
          description: 성공
          content:
            text/plain:
              schema:
                type: string
                example: Hello World!