name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "===== 배포 시작 ====="
            cd ~/neordinaryu-be
            
            # 최신 코드 가져오기
            git fetch origin main
            git reset --hard origin/main
            
            # 필요한 종속성 설치
            npm ci
            
            # Prisma 처리
            npx prisma generate
            npx prisma migrate deploy
            
            # 애플리케이션 빌드 (postbuild 스크립트에서 Swagger 파일이 자동으로 복사됨)
            npm run build
            
            # PM2로 서비스 재시작
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            # 이미 실행 중이면 재시작, 없으면 새로 시작
            pm2 describe neordinaryu-be > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart neordinaryu-be
            else
              pm2 start npm --name "neordinaryu-be" -- start
            fi
            
            # 재부팅시 자동 시작 설정
            pm2 save
            
            echo "===== 배포 완료 ====="